### PR TITLE
Test for fork-based pull requests

### PR DESCRIPTION
**Pull request by dpnkrpl**
This is just to test if it pass or not on a fork-based pull request

### CODE REVIEW

**Comment by dpnkrpl** [comment]
hi @bubkoo as you can see it fails on a pull request originating from a fork. 
There is an event called `pull_request_target` in the API. I think that event is responsible for fork-basedPRs.
### Thank you

**Comment by bubkoo** [comment]
@deep5050 You can use `'pull_request_target'` for the triggered event and config like this: 

```yml
name: Auto Comment
on: [issues, pull_request_target]
jobs:
```

**Comment by dpnkrpl** [comment]
as I dont have another account to test it on myself. would you please update your workflow file for a while so that i can test it :smile:

It would be great.

**Comment by bubkoo** [comment]
test comment

**Comment by dpnkrpl** [comment]
test 1

**Comment by dpnkrpl** [comment]
opening another PR

**Comment by bubkoo** [comment]
> opening another PR

It's work

**Comment by dpnkrpl** [comment]
you can now close all the issues. 
Thanks

**Pull request closed without merging**
